services:
  # Servicio web principal
  - type: web
    name: doctorfy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    disk:
      name: uploads
      mountPath: /persistent
      sizeGB: 10
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: doctorfy-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: PORT
        value: 8000

  # Base de datos PostgreSQL
databases:
  - name: doctorfy-db
    plan: free
    databaseName: doctorfy
    user: doctorfy_user 