services:
  # Servicio web principal
  - type: web
    name: doctorfy
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: doctorfy-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: PORT
        value: 8000
      - key: ALLOWED_ORIGINS
        value: https://doctorfy-frontend.onrender.com
      - key: FLASK_ENV
        value: production
      - key: SERVE_FRONTEND
        value: "false"

  # Base de datos PostgreSQL
databases:
  - name: doctorfy-db
    plan: free
    databaseName: doctorfy
    user: doctorfy_user 