services:
  # Servicio web principal
  - type: web
    name: doctorfy
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: doctorfy-db
          property: connectionString
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1

# Base de datos PostgreSQL
databases:
  - name: doctorfy-db
    plan: starter
    databaseName: doctorfy
    user: doctorfy_user 