"""mensaje descriptivo

Revision ID: 2187dd491d20
Revises: c30e2bf7840a
Create Date: 2025-04-17 13:34:04.896823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2187dd491d20'
down_revision = 'c30e2bf7840a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trial_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('trial_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('trial_used', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('trial_used')
        batch_op.drop_column('trial_end')
        batch_op.drop_column('trial_start')

    # ### end Alembic commands ###
