"""Calorias

Revision ID: 250d10b3a2e5
Revises: c62b4d71e883
Create Date: 2025-04-25 17:14:09.573123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250d10b3a2e5'
down_revision = 'c62b4d71e883'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('physical_activities', schema=None) as batch_op:
        batch_op.alter_column('activity_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('calories_burned',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False)
        batch_op.drop_column('intensity')
        batch_op.drop_column('notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('physical_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('intensity', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.alter_column('calories_burned',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('activity_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
