"""Add study status enum, interpretation, timestamps and other model updates

Revision ID: 4646c3b97fd7
Revises: 1ca1af9737f4
Create Date: 2023-XX-XX XX:XX:XX.XXXXXX

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4646c3b97fd7'
down_revision = '1ca1af9737f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### Primero crear el tipo enum en PostgreSQL ###
    studystatus = postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='studystatus')
    studystatus.create(op.get_bind())
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_studies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='studystatus'), nullable=False, server_default='PENDING'))
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('study_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'doctors', ['doctor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_studies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('study_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('status')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('doctor_id')

    # ### end Alembic commands ###
    
    # ### Eliminar el tipo enum de PostgreSQL ###
    sa.Enum(name='studystatus').drop(op.get_bind())
