"""Add BlogPost model 2

Revision ID: f908347061bb
Revises: 131c4bf3e9d1
Create Date: 2025-04-28 20:52:12.454405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f908347061bb'
down_revision = '131c4bf3e9d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('meta_keywords', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_column('meta_keywords')
        batch_op.drop_column('meta_title')

    # ### end Alembic commands ###
